services:
  db:
    image: postgres:16.4-alpine3.20
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  server:
    image:
      context: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
