/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: src/proto/message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   msg__v1__chat_message__init
                     (Msg__V1__ChatMessage         *message)
{
  static const Msg__V1__ChatMessage init_value = MSG__V1__CHAT_MESSAGE__INIT;
  *message = init_value;
}
size_t msg__v1__chat_message__get_packed_size
                     (const Msg__V1__ChatMessage *message)
{
  assert(message->base.descriptor == &msg__v1__chat_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__v1__chat_message__pack
                     (const Msg__V1__ChatMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__v1__chat_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__v1__chat_message__pack_to_buffer
                     (const Msg__V1__ChatMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__v1__chat_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__V1__ChatMessage *
       msg__v1__chat_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__V1__ChatMessage *)
     protobuf_c_message_unpack (&msg__v1__chat_message__descriptor,
                                allocator, len, data);
}
void   msg__v1__chat_message__free_unpacked
                     (Msg__V1__ChatMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__v1__chat_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__v1__move_message__init
                     (Msg__V1__MoveMessage         *message)
{
  static const Msg__V1__MoveMessage init_value = MSG__V1__MOVE_MESSAGE__INIT;
  *message = init_value;
}
size_t msg__v1__move_message__get_packed_size
                     (const Msg__V1__MoveMessage *message)
{
  assert(message->base.descriptor == &msg__v1__move_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__v1__move_message__pack
                     (const Msg__V1__MoveMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__v1__move_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__v1__move_message__pack_to_buffer
                     (const Msg__V1__MoveMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__v1__move_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__V1__MoveMessage *
       msg__v1__move_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__V1__MoveMessage *)
     protobuf_c_message_unpack (&msg__v1__move_message__descriptor,
                                allocator, len, data);
}
void   msg__v1__move_message__free_unpacked
                     (Msg__V1__MoveMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__v1__move_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue msg__v1__chat_message__scope__enum_values_by_number[5] =
{
  { "PRIVATE", "MSG__V1__CHAT_MESSAGE__SCOPE__PRIVATE", 0 },
  { "PARTY", "MSG__V1__CHAT_MESSAGE__SCOPE__PARTY", 1 },
  { "GUILD", "MSG__V1__CHAT_MESSAGE__SCOPE__GUILD", 2 },
  { "LOCAL", "MSG__V1__CHAT_MESSAGE__SCOPE__LOCAL", 3 },
  { "GLOBAL", "MSG__V1__CHAT_MESSAGE__SCOPE__GLOBAL", 4 },
};
static const ProtobufCIntRange msg__v1__chat_message__scope__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex msg__v1__chat_message__scope__enum_values_by_name[5] =
{
  { "GLOBAL", 4 },
  { "GUILD", 2 },
  { "LOCAL", 3 },
  { "PARTY", 1 },
  { "PRIVATE", 0 },
};
const ProtobufCEnumDescriptor msg__v1__chat_message__scope__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "msg.v1.ChatMessage.Scope",
  "Scope",
  "Msg__V1__ChatMessage__Scope",
  "msg.v1",
  5,
  msg__v1__chat_message__scope__enum_values_by_number,
  5,
  msg__v1__chat_message__scope__enum_values_by_name,
  1,
  msg__v1__chat_message__scope__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor msg__v1__chat_message__field_descriptors[4] =
{
  {
    "scope",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Msg__V1__ChatMessage, scope),
    &msg__v1__chat_message__scope__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Msg__V1__ChatMessage, sender),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recipient",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Msg__V1__ChatMessage, recipient),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__V1__ChatMessage, content),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__v1__chat_message__field_indices_by_name[] = {
  3,   /* field[3] = content */
  2,   /* field[2] = recipient */
  0,   /* field[0] = scope */
  1,   /* field[1] = sender */
};
static const ProtobufCIntRange msg__v1__chat_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor msg__v1__chat_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.v1.ChatMessage",
  "ChatMessage",
  "Msg__V1__ChatMessage",
  "msg.v1",
  sizeof(Msg__V1__ChatMessage),
  4,
  msg__v1__chat_message__field_descriptors,
  msg__v1__chat_message__field_indices_by_name,
  1,  msg__v1__chat_message__number_ranges,
  (ProtobufCMessageInit) msg__v1__chat_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__v1__move_message__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Msg__V1__MoveMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Msg__V1__MoveMessage, map),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Msg__V1__MoveMessage, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__V1__MoveMessage, y),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__v1__move_message__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = map */
  2,   /* field[2] = x */
  3,   /* field[3] = y */
};
static const ProtobufCIntRange msg__v1__move_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor msg__v1__move_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.v1.MoveMessage",
  "MoveMessage",
  "Msg__V1__MoveMessage",
  "msg.v1",
  sizeof(Msg__V1__MoveMessage),
  4,
  msg__v1__move_message__field_descriptors,
  msg__v1__move_message__field_indices_by_name,
  1,  msg__v1__move_message__number_ranges,
  (ProtobufCMessageInit) msg__v1__move_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
