/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: src/proto/message.proto */

#ifndef PROTOBUF_C_src_2fproto_2fmessage_2eproto__INCLUDED
#define PROTOBUF_C_src_2fproto_2fmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Msg__V1__ChatMessage Msg__V1__ChatMessage;
typedef struct _Msg__V1__MoveMessage Msg__V1__MoveMessage;


/* --- enums --- */

typedef enum _Msg__V1__ChatMessage__Scope {
  MSG__V1__CHAT_MESSAGE__SCOPE__PRIVATE = 0,
  MSG__V1__CHAT_MESSAGE__SCOPE__PARTY = 1,
  MSG__V1__CHAT_MESSAGE__SCOPE__GUILD = 2,
  MSG__V1__CHAT_MESSAGE__SCOPE__LOCAL = 3,
  MSG__V1__CHAT_MESSAGE__SCOPE__GLOBAL = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MSG__V1__CHAT_MESSAGE__SCOPE)
} Msg__V1__ChatMessage__Scope;

/* --- messages --- */

struct  _Msg__V1__ChatMessage
{
  ProtobufCMessage base;
  Msg__V1__ChatMessage__Scope scope;
  uint64_t sender;
  uint64_t recipient;
  char *content;
};
#define MSG__V1__CHAT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&msg__v1__chat_message__descriptor) \
    , MSG__V1__CHAT_MESSAGE__SCOPE__PRIVATE, 0, 0, (char *)protobuf_c_empty_string }


struct  _Msg__V1__MoveMessage
{
  ProtobufCMessage base;
  uint64_t id;
  uint64_t map;
  uint64_t x;
  char *y;
};
#define MSG__V1__MOVE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&msg__v1__move_message__descriptor) \
    , 0, 0, 0, (char *)protobuf_c_empty_string }


/* Msg__V1__ChatMessage methods */
void   msg__v1__chat_message__init
                     (Msg__V1__ChatMessage         *message);
size_t msg__v1__chat_message__get_packed_size
                     (const Msg__V1__ChatMessage   *message);
size_t msg__v1__chat_message__pack
                     (const Msg__V1__ChatMessage   *message,
                      uint8_t             *out);
size_t msg__v1__chat_message__pack_to_buffer
                     (const Msg__V1__ChatMessage   *message,
                      ProtobufCBuffer     *buffer);
Msg__V1__ChatMessage *
       msg__v1__chat_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   msg__v1__chat_message__free_unpacked
                     (Msg__V1__ChatMessage *message,
                      ProtobufCAllocator *allocator);
/* Msg__V1__MoveMessage methods */
void   msg__v1__move_message__init
                     (Msg__V1__MoveMessage         *message);
size_t msg__v1__move_message__get_packed_size
                     (const Msg__V1__MoveMessage   *message);
size_t msg__v1__move_message__pack
                     (const Msg__V1__MoveMessage   *message,
                      uint8_t             *out);
size_t msg__v1__move_message__pack_to_buffer
                     (const Msg__V1__MoveMessage   *message,
                      ProtobufCBuffer     *buffer);
Msg__V1__MoveMessage *
       msg__v1__move_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   msg__v1__move_message__free_unpacked
                     (Msg__V1__MoveMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Msg__V1__ChatMessage_Closure)
                 (const Msg__V1__ChatMessage *message,
                  void *closure_data);
typedef void (*Msg__V1__MoveMessage_Closure)
                 (const Msg__V1__MoveMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor msg__v1__chat_message__descriptor;
extern const ProtobufCEnumDescriptor    msg__v1__chat_message__scope__descriptor;
extern const ProtobufCMessageDescriptor msg__v1__move_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_src_2fproto_2fmessage_2eproto__INCLUDED */
